<?php require_once './templates/header.phtml' ?>

<form method='POST' action='game-edited/<?= $game->juegoId ?>'>
    <div class="form-group">
      <label for="nombreJuego">Nombre</label>
      <input type="text" class="form-control" id="nombreJuego" name='nombreJuego' placeholder="Nombre del juego" value='<?= $game->nombreJuego ?>'>
    </div>
    <div class="form-group">
      <label for="fechaLanzamiento">Nombre</label>
      <input type="date" class="form-control" id="fechaLanzamiento" name='fechaLanzamiento' placeholder="Fecha de creación" value='<?= $game->fechaLanzamiento ?>'>
    </div>
    <div class="form-group">
        <label for="desarrolladorId">Desarrollador</label>
        <select class="form-control" name='desarrolladorId' id='desarrolladorId'>
            <?php foreach($devs as $dev): ?>
            <option <?php if($game->desarrolladorId == $dev->desarrolladorId): ?>selected<?php endif ?> value='<?= $dev->desarrolladorId ?>'><?= $dev->nombreDesarrollador ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="form-group">
        <label for="edad">Edad mínima</label>
        <input type="number" min='0' class="form-control" id="edad" name='edad' placeholder="Edad mínima" value='<?= $game->edad ?>'>
    </div>
    <div class="form-group">
        <label for="descripcionJuego">Descripción del juego</label>
        <textarea class="form-control" id="descripcionJuego" name='descripcionJuego' placeholder="Descripción del juego"><?= $game->descripcionJuego ?></textarea>
    </div><div class="form-group">
        <label for="imagen">Imagen</label>
        <input type="text" class="form-control" id="imagen" name='imagen' value='<?= $game->imagen ?>' placeholder="Inserte el link de la imagen">
    </div>
    <button type="submit" class="btn btn-primary">Editar</button>
</form>

<?php require_once './templates/footer.phtml' ?>