</main>
<!-- fin main container -->

<!-- main footer -->
<footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top border-dark">
      <div class="align-items-center">
        <span class="text-muted">
          Bienvenido tienda del 
          <a href="https://yugioh.fandom.com/es/wiki/Ciber_Drag%C3%B3n">Ciber Dragon</a>, 
          listo para Observar el 
          <a href="https://www.youtube.com/watch?v=0J6j0dyZHxg">gran poder de los ciber dragones.</a>
        </span>
      </div>
</footer>

<!-- estilos personalizados -->
<style> 
  footer a {
    text-decoration: none;      /* quita el subrayado */
    color: rgb(0, 0, 0);        /* color normal */
    transition: color 0.3s;     /* transición suave */
  }

  footer a:hover {
    color: #FFD700;             /* dorado brillante */
    font-weight: bold;          /* opcional */
  }

  footer {
    bottom: 0;         /* siempre al fondo */
    left: 0;
    width: 100%;       /* ocupa todo el ancho */
    background: #f8f9fa; /* mismo color que navbar bootstrap */
  }
</style>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>
