<!DOCTYPE html> 
    <html lang="en"> 
    <!-- head --> 
    <head> 
        <meta charset="UTF-8">
        <base href="<?= BASE_URL ?>"> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"> 
        <link rel="stylesheet" href="css/style.css" type="text/css" /> 
        <link rel="icon" type="image/png" href="css\imagenes extras\logo2.jpg">
        <title>Ciber Dragon</title> 
    </head> 
        <body> 
            <!-- main header --> 
            <header> 
                <nav class="navbar navbar-expand-lg bg-light"> 
                    <div class="container-fluid"> 
                        <a class="navbar-brand" href="games"><img src="css\imagenes extras\logo.jpg" width="70" height="70" class="img-logo">Lista de juegos</a> 
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> 
                            <span class="navbar-toggler-icon"></span> </button> <div class="collapse navbar-collapse" id="navbarNav"> 
                                <ul class="navbar-nav"> 
                                    <li class="nav-item"> 
                                        <a class="nav-link" aria-current="page" href="games">Juegos</a> 
                                    </li> 
                                    <li class="nav-item"> 
                                        <a class="nav-link" aria-current="page" href="developers">Desarrolladores</a> 
                                    </li> <?php if (!AuthHelper::isLogged()) : ?> 
                                    <li class="nav-item"> 
                                        <a class="nav-link" aria-current="page" href="login">Login</a> 
                                    </li> <?php else : ?> 
                                    <li class="nav-item"> 
                                    <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_USERNAME'] ?>)</a> 
                                    </li> <?php endif ?> 
                                </ul> 
                            </div> 
                        </div> 
                    </nav> 
                </header> 
                <!-- inicio main container --> 
                 <main class="container mt-3">
<style>
  .img-logo {
    border: 3px solid black; 
    border-radius: 50%;      
    transition: border-color 0.3s; 
  }

  .img-logo:hover {
    border-color: gold;       
  }

  body {
        background-color: rgb(126, 126, 126);
}

main {
        background-color: rgb(126, 126, 126);
}
</style>